'use client'

import { useState, useTransition, type FormEvent, type ReactNode } from 'react'
import { useRouter } from 'next/navigation'

import { DoctorScheduleForm } from '@/components/schedule/doctor-schedule-form'
import { saveAppointmentType, deleteAppointmentType, saveAssistantSettings, saveDepositRule, deleteDepositRule, reorderDepositRules, saveIntakeField, deleteIntakeField, saveKnowledgeItem, deleteKnowledgeItem, savePaymentInstructions, type AssistantActionState } from '@/lib/assistant/assistant-configuration'
import { sortDepositRules, type DepositRule } from '@/lib/assistant/deposit-rules'
import type { DoctorSchedule, RecurringUnavailability } from '@/lib/schedule/doctor-schedule'

type AppointmentType = { id: string; name: string; duration_minutes: number; price: number | null; is_active: boolean }
type IntakeField = { id: string; field_key: string; label: string; is_required: boolean; is_active: boolean; sort_order: number }
type KnowledgeItem = { id: string; title: string; content: string; is_active: boolean; sort_order: number }
type Settings = { assistant_name: string | null; confirmation_enabled: boolean | null; confirmation_lead_minutes: number | null; confirmation_response_window_minutes: number | null; unconfirmed_action: 'CANCEL' | 'MANUAL' | null; manual_follow_up_on_no_answer: boolean }
type Payment = { bank_name: string | null; account_holder: string | null; clabe: string | null; account_number: string | null; instructions: string | null; message_template: string | null }

function Card({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <section className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-semibold tracking-tight text-zinc-950">{title}</h2>{description ? <p className="mt-2 text-sm leading-6 text-zinc-600">{description}</p> : null}<div className="mt-5">{children}</div></section> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-medium text-zinc-600">{label}<span className="mt-1 block">{children}</span></label> }
const inputClass = 'w-full rounded-md border border-zinc-300 bg-white px-2.5 py-2 text-sm'

function ActionForm({ action, doctorId, children, className = '' }: { action: (formData: FormData) => Promise<AssistantActionState>; doctorId: string; children: ReactNode; className?: string }) {
  const [pending, startTransition] = useTransition(); const [feedback, setFeedback] = useState<AssistantActionState>({}); const router = useRouter()
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; startTransition(async () => { const result = await action(new FormData(form)); setFeedback(result); if (result.success) router.refresh() }) }
  return <form onSubmit={submit} className={className}><input type="hidden" name="doctor_id" value={doctorId} />{children}{feedback.error ? <p className="mt-3 text-sm text-red-700" role="alert">{feedback.error}</p> : null}{feedback.success ? <p className="mt-3 text-sm text-emerald-700" role="status">{feedback.success}</p> : null}<button type="submit" disabled={pending} className="mt-4 rounded-lg bg-zinc-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{pending ? 'Guardando…' : 'Guardar'}</button></form>
}

function DeleteButton({ action, doctorId, id }: { action: (formData: FormData) => Promise<AssistantActionState>; doctorId: string; id: string }) { const [pending, startTransition] = useTransition(); const router = useRouter(); return <button type="button" disabled={pending} onClick={() => { if (!window.confirm('¿Eliminar este registro?')) return; const data = new FormData(); data.set('doctor_id', doctorId); data.set('id', id); startTransition(async () => { await action(data); router.refresh() }) }} className="text-xs font-medium text-red-700 disabled:opacity-50">{pending ? 'Eliminando…' : 'Eliminar'}</button> }

function Toggle({ name, checked, label }: { name: string; checked?: boolean; label: string }) { return <label className="flex items-center gap-2 text-sm text-zinc-700"><input type="checkbox" name={name} defaultChecked={checked} />{label}</label> }

function ConfirmationFields({ settings }: { settings: Settings }) {
  return <div className="mt-4 space-y-4">
    <input type="hidden" name="manual_follow_up_on_no_answer" value={String(settings.manual_follow_up_on_no_answer)} />
    <Field label="¿Quieres que tu asistente confirme las citas?"><select name="confirmation_enabled" className={inputClass} defaultValue={settings.confirmation_enabled === true ? 'true' : settings.confirmation_enabled === false ? 'false' : ''}><option value="">Selecciona una opción</option><option value="true">Sí</option><option value="false">No</option></select></Field>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="¿Cuándo quieres que llame?"><select name="confirmation_lead_minutes" className={inputClass} defaultValue={String(settings.confirmation_lead_minutes ?? 240)}><option value="240">El mismo día</option><option value="1440">1 día antes</option><option value="2880">2 días antes</option></select></Field><Field label="Después del recordatorio, ¿cuánto tiempo quieres esperar?"><select name="confirmation_response_window_minutes" className={inputClass} defaultValue={String(settings.confirmation_response_window_minutes ?? 240)}><option value="120">2 horas</option><option value="240">4 horas</option><option value="480">8 horas</option><option value="720">12 horas</option><option value="1440">24 horas</option></select></Field></div>
    <Field label="Si el paciente no confirma, ¿qué quieres que haga tu asistente?"><select name="unconfirmed_action" className={inputClass} defaultValue={settings.unconfirmed_action ?? ''}><option value="">Selecciona una opción</option><option value="CANCEL">Cancelar la cita automáticamente</option><option value="MANUAL">Dejarla pendiente para decisión manual</option></select></Field>
  </div>
}

export function AssistantConfiguration({ doctorId, doctor, timezone, schedule, recurringUnavailability, settings, payment, appointmentTypes, intakeFields, depositRules, knowledgeItems }: { doctorId: string; doctor: { display_name: string; specialty: string | null; address: string | null; phone: string | null; whatsapp: string | null }; timezone: string; schedule: DoctorSchedule; recurringUnavailability: RecurringUnavailability[]; settings: Settings | null; payment: Payment | null; appointmentTypes: AppointmentType[]; intakeFields: IntakeField[]; depositRules: DepositRule[]; knowledgeItems: KnowledgeItem[] }) {
  const currentSettings = settings ?? { assistant_name: null, confirmation_enabled: null, confirmation_lead_minutes: 240, confirmation_response_window_minutes: 240, unconfirmed_action: null, manual_follow_up_on_no_answer: true }
  return <section className="max-w-4xl space-y-8"><header><p className="text-sm font-semibold tracking-wide text-zinc-500">HelloPx · DOCTOR</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-zinc-950">Capacita a tu asistente</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-600">Configura la información y las reglas que utilizará tu asistente para orientar a tus pacientes y ayudarte a gestionar citas.</p></header>
    <Card title="Tu asistente" description="Puedes cambiar este nombre cuando quieras."><ActionForm action={saveAssistantSettings} doctorId={doctorId}><Field label="Nombre del asistente"><input name="assistant_name" className={inputClass} defaultValue={currentSettings.assistant_name ?? ''} placeholder="Nombre del asistente" /></Field><ConfirmationFields settings={currentSettings} /></ActionForm></Card>
    <Card title="Tu consultorio" description="Estos datos se muestran actualmente como referencia. La edición por DOCTOR queda pendiente de habilitarse de forma segura."><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre"><input className={inputClass} value={doctor.display_name} readOnly /></Field><Field label="Especialidad"><input className={inputClass} value={doctor.specialty ?? '—'} readOnly /></Field><Field label="Dirección"><input className={inputClass} value={doctor.address ?? '—'} readOnly /></Field><Field label="Teléfono"><input className={inputClass} value={doctor.phone ?? '—'} readOnly /></Field><Field label="WhatsApp"><input className={inputClass} value={doctor.whatsapp ?? '—'} readOnly /></Field></div></Card>
    <Card title="Zona horaria" description="Se reutiliza la zona horaria operativa del doctor para la agenda y el asistente."><p className="rounded-md bg-zinc-50 px-3 py-2 font-mono text-sm text-zinc-800">{timezone}</p></Card>
    <Card title="Cuándo atiendes" description="Este es el mismo horario habitual que utiliza la Agenda."><DoctorScheduleForm doctorId={doctorId} schedule={schedule} recurringUnavailability={recurringUnavailability} showRecurringUnavailability /></Card>
    <AppointmentTypes doctorId={doctorId} items={appointmentTypes} />
    <IntakeFields doctorId={doctorId} items={intakeFields} />
    <DepositRules doctorId={doctorId} items={depositRules} appointmentTypes={appointmentTypes} intakeFields={intakeFields} />
    <Card title="Cómo recibir el anticipo" description="Son datos operativos que se incluirán posteriormente en mensajes de pago; no son credenciales de acceso bancario."><ActionForm action={savePaymentInstructions} doctorId={doctorId} className="grid gap-4 sm:grid-cols-2"><Field label="Banco"><input name="bank_name" className={inputClass} defaultValue={payment?.bank_name ?? ''} /></Field><Field label="Titular"><input name="account_holder" className={inputClass} defaultValue={payment?.account_holder ?? ''} /></Field><Field label="CLABE"><input name="clabe" className={inputClass} defaultValue={payment?.clabe ?? ''} /></Field><Field label="Número de cuenta"><input name="account_number" className={inputClass} defaultValue={payment?.account_number ?? ''} /></Field><Field label="Instrucciones"><textarea name="instructions" className={inputClass} rows={3} defaultValue={payment?.instructions ?? ''} /></Field><Field label="Mensaje base"><textarea name="message_template" className={inputClass} rows={3} defaultValue={payment?.message_template ?? ''} /></Field></ActionForm></Card>
    <KnowledgeItems doctorId={doctorId} items={knowledgeItems} />
  </section>
}

function AppointmentTypes({ doctorId, items }: { doctorId: string; items: AppointmentType[] }) { return <Card title="Qué citas manejas" description="Define los tipos de cita y su duración. Todavía no se relacionan con appointments."><div className="space-y-4">{items.map((item) => <ActionForm key={item.id} action={saveAppointmentType} doctorId={doctorId} className="rounded-lg bg-zinc-50 p-4"><input type="hidden" name="id" value={item.id} /><div className="grid gap-3 sm:grid-cols-[1fr_150px_130px_auto]"><input name="name" className={inputClass} defaultValue={item.name} aria-label="Nombre" /><input name="duration_minutes" type="number" min="1" className={inputClass} defaultValue={item.duration_minutes} aria-label="Duración" /><input name="price" type="number" min="0" step="0.01" className={inputClass} defaultValue={item.price ?? ''} placeholder="Precio" aria-label="Precio" /><Toggle name="is_active" checked={item.is_active} label="Activo" /></div><DeleteButton action={deleteAppointmentType} doctorId={doctorId} id={item.id} /></ActionForm>)}{!items.length ? <p className="text-sm text-zinc-500">Aún no hay tipos de cita.</p> : null}<ActionForm action={saveAppointmentType} doctorId={doctorId} className="border-t border-zinc-200 pt-4"><div className="grid gap-3 sm:grid-cols-4"><input name="name" className={inputClass} placeholder="Primera consulta" aria-label="Nombre" required /><input name="duration_minutes" type="number" min="1" className={inputClass} placeholder="Duración" aria-label="Duración" required /><input name="price" type="number" min="0" step="0.01" className={inputClass} placeholder="Precio opcional" aria-label="Precio" /><Toggle name="is_active" checked label="Activo" /></div></ActionForm></div></Card> }

function IntakeFields({ doctorId, items }: { doctorId: string; items: IntakeField[] }) { return <Card title="Qué debe preguntar" description="Ordena los campos con el número de orden. No se almacenan respuestas aquí."><div className="space-y-4">{items.map((item) => <ActionForm key={item.id} action={saveIntakeField} doctorId={doctorId} className="rounded-lg bg-zinc-50 p-4"><input type="hidden" name="id" value={item.id} /><div className="grid gap-3 sm:grid-cols-[150px_1fr_90px] sm:items-end"><Field label="Clave"><input name="field_key" className={inputClass} defaultValue={item.field_key} required /></Field><Field label="Etiqueta"><input name="label" className={inputClass} defaultValue={item.label} required /></Field><Field label="Orden"><input name="sort_order" type="number" min="0" className={inputClass} defaultValue={item.sort_order} required /></Field></div><div className="mt-3 flex flex-wrap gap-4"><Toggle name="is_required" checked={item.is_required} label="Requerido" /><Toggle name="is_active" checked={item.is_active} label="Activo" /></div><DeleteButton action={deleteIntakeField} doctorId={doctorId} id={item.id} /></ActionForm>)}<ActionForm action={saveIntakeField} doctorId={doctorId} className="border-t border-zinc-200 pt-4"><div className="grid gap-3 sm:grid-cols-[150px_1fr_90px]"><input name="field_key" className={inputClass} placeholder="origin_city" required /><input name="label" className={inputClass} placeholder="Ciudad de origen" required /><input name="sort_order" type="number" min="0" className={inputClass} defaultValue="0" required /></div><div className="mt-3 flex gap-4"><Toggle name="is_required" label="Requerido" /><Toggle name="is_active" checked label="Activo" /></div></ActionForm></div></Card> }

function DepositRules({ doctorId, items, appointmentTypes, intakeFields }: { doctorId: string; items: DepositRule[]; appointmentTypes: AppointmentType[]; intakeFields: IntakeField[] }) {
  const [pending, startTransition] = useTransition()
  const [feedback, setFeedback] = useState<AssistantActionState>({})
  const router = useRouter()
  const orderedItems = sortDepositRules(items)

  function moveRule(index: number, direction: -1 | 1) {
    const target = index + direction
    if (target < 0 || target >= orderedItems.length || pending) return
    const ids = orderedItems.map((item) => item.id)
    ;[ids[index], ids[target]] = [ids[target], ids[index]]
    const formData = new FormData()
    formData.set('doctor_id', doctorId)
    formData.set('ids', JSON.stringify(ids))
    setFeedback({})
    startTransition(async () => {
      const result = await reorderDepositRules(formData)
      setFeedback(result)
      if (result.success) router.refresh()
    })
  }

  return <Card title="Cuándo pedir anticipo" description="Estas reglas sólo capacitan al asistente. No activan pagos ni el estado WAITING_DEPOSIT."><div className="space-y-4"><p className="text-sm text-zinc-600">Si más de una regla aplica, se usará la primera.</p>{orderedItems.map((item, index) => <div key={item.id} className="rounded-lg bg-zinc-50 p-4"><div className="mb-3 flex items-center justify-between gap-3"><p className="text-sm font-medium text-zinc-800">Prioridad {index + 1}</p><div className="flex gap-3"><button type="button" disabled={pending || index === 0} onClick={() => moveRule(index, -1)} aria-label="Subir prioridad" className="text-sm text-zinc-600 disabled:opacity-30">↑ Subir</button><button type="button" disabled={pending || index === orderedItems.length - 1} onClick={() => moveRule(index, 1)} aria-label="Bajar prioridad" className="text-sm text-zinc-600 disabled:opacity-30">↓ Bajar</button></div></div><DepositRuleForm doctorId={doctorId} item={item} appointmentTypes={appointmentTypes} intakeFields={intakeFields} /></div>)}{feedback.error ? <p className="text-sm text-red-700" role="alert">{feedback.error}</p> : null}<h3 className="border-t border-zinc-200 pt-4 text-sm font-medium text-zinc-800">Agregar una regla</h3><NewDepositRuleForm doctorId={doctorId} appointmentTypes={appointmentTypes} intakeFields={intakeFields} /></div></Card>
}

function DepositRuleForm({ doctorId, item, appointmentTypes, intakeFields }: { doctorId: string; item: DepositRule; appointmentTypes: AppointmentType[]; intakeFields: IntakeField[] }) {
  const [scope, setScope] = useState(item.scope)
  return <ActionForm action={saveDepositRule} doctorId={doctorId}>
    <input type="hidden" name="id" value={item.id} /><input type="hidden" name="sort_order" value={item.sort_order} />
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Nombre"><input name="name" className={inputClass} defaultValue={item.name} required /></Field><Field label="Aplica a"><select name="scope" className={inputClass} value={scope} onChange={(event) => setScope(event.target.value as DepositRule['scope'])}><option value="ALL">Todos</option><option value="APPOINTMENT_TYPE">Tipo de cita</option><option value="INTAKE_FIELD">Dato del paciente</option></select></Field>
      {scope === 'APPOINTMENT_TYPE' ? <Field label="Tipo de cita"><select name="appointment_type_id" className={inputClass} defaultValue={item.appointment_type_id ?? ''} required><option value="">Selecciona un tipo</option>{appointmentTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></Field> : null}
      {scope === 'INTAKE_FIELD' ? <><Field label="Pregunta"><select name="intake_field_id" className={inputClass} defaultValue={item.intake_field_id ?? ''} required><option value="">Selecciona una pregunta</option>{intakeFields.map((field) => <option key={field.id} value={field.id}>{field.label}</option>)}</select></Field><input type="hidden" name="operator" value="EQUALS" /><Field label="Respuesta"><input name="condition_value" className={inputClass} defaultValue={item.condition_value ?? ''} required /></Field></> : null}
      <Field label="Cantidad de anticipo"><div className="flex items-center"><span className="rounded-l-lg border border-r-0 border-zinc-300 bg-zinc-50 px-3 py-2 text-sm text-zinc-500">$</span><input name="deposit_value" type="number" min="0.01" step="0.01" className={`${inputClass} rounded-l-none`} defaultValue={item.deposit_type === 'PERCENTAGE' ? '' : item.deposit_value} placeholder="Ej. 500" /></div></Field>
    </div><div className="mt-3"><Toggle name="is_active" checked={item.is_active} label="Activa" /></div><DeleteButton action={deleteDepositRule} doctorId={doctorId} id={item.id} />
    {item.deposit_type === 'PERCENTAGE' ? <p className="mt-3 text-xs leading-5 text-amber-700">Esta regla usaba porcentaje. Ingresa una cantidad de anticipo para actualizarla.</p> : null}
  </ActionForm>
}

function NewDepositRuleForm({ doctorId, appointmentTypes, intakeFields }: { doctorId: string; appointmentTypes: AppointmentType[]; intakeFields: IntakeField[] }) {
  const [scope, setScope] = useState<DepositRule['scope']>('ALL')
  return <ActionForm action={saveDepositRule} doctorId={doctorId} className="border-t border-zinc-200 pt-4">
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Nombre"><input name="name" className={inputClass} placeholder="Regla de anticipo" required /></Field><Field label="Aplica a"><select name="scope" className={inputClass} value={scope} onChange={(event) => setScope(event.target.value as DepositRule['scope'])}><option value="ALL">Todos</option><option value="APPOINTMENT_TYPE">Tipo de cita</option><option value="INTAKE_FIELD">Dato del paciente</option></select></Field>
      {scope === 'APPOINTMENT_TYPE' ? <Field label="Tipo de cita"><select name="appointment_type_id" className={inputClass} defaultValue="" required><option value="">Selecciona un tipo</option>{appointmentTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></Field> : null}
      {scope === 'INTAKE_FIELD' ? <><Field label="Pregunta"><select name="intake_field_id" className={inputClass} defaultValue="" required><option value="">Selecciona una pregunta</option>{intakeFields.map((field) => <option key={field.id} value={field.id}>{field.label}</option>)}</select></Field><input type="hidden" name="operator" value="EQUALS" /><Field label="Respuesta"><input name="condition_value" className={inputClass} placeholder="Escribe una respuesta" required /></Field></> : null}
      <Field label="Cantidad de anticipo"><div className="flex items-center"><span className="rounded-l-lg border border-r-0 border-zinc-300 bg-zinc-50 px-3 py-2 text-sm text-zinc-500">$</span><input name="deposit_value" type="number" min="0.01" step="0.01" className={`${inputClass} rounded-l-none`} placeholder="Ej. 500" required /></div></Field>
    </div><div className="mt-3"><Toggle name="is_active" checked label="Activa" /></div>
  </ActionForm>
}

function KnowledgeItems({ doctorId, items }: { doctorId: string; items: KnowledgeItem[] }) { return <Card title="Qué puede responder" description="Agrega información administrativa autorizada. No incluyas diagnóstico, expediente ni indicaciones clínicas."><div className="space-y-4">{items.map((item) => <ActionForm key={item.id} action={saveKnowledgeItem} doctorId={doctorId} className="rounded-lg bg-zinc-50 p-4"><input type="hidden" name="id" value={item.id} /><div className="grid gap-3 sm:grid-cols-[1fr_90px]"><input name="title" className={inputClass} defaultValue={item.title} placeholder="Título" required /><input name="sort_order" type="number" min="0" className={inputClass} defaultValue={item.sort_order} aria-label="Orden" required /></div><textarea name="content" className={`${inputClass} mt-3`} rows={4} defaultValue={item.content} required /><div className="mt-3 flex gap-4"><Toggle name="is_active" checked={item.is_active} label="Activo" /></div><DeleteButton action={deleteKnowledgeItem} doctorId={doctorId} id={item.id} /></ActionForm>)}<ActionForm action={saveKnowledgeItem} doctorId={doctorId} className="border-t border-zinc-200 pt-4"><div className="grid gap-3 sm:grid-cols-[1fr_90px]"><input name="title" className={inputClass} placeholder="Estacionamiento" required /><input name="sort_order" type="number" min="0" className={inputClass} defaultValue="0" aria-label="Orden" required /></div><textarea name="content" className={`${inputClass} mt-3`} rows={4} placeholder="Información que el asistente puede compartir" required /><div className="mt-3"><Toggle name="is_active" checked label="Activo" /></div></ActionForm></div></Card> }
